### ISSUE TITLE
Brew install on Mac Fails

### ISSUE THREAD

**Issue by unimercio** [ethcore/parity#1938]
Trying to install parity on Mac OSX 10.10.5  using below 

$ **brew tap ethcore/ethcore**
$ **brew install parity**

Gives this error:

==> Auto-updated Homebrew!
Updated Homebrew from b630ab3 to 984ed83.
Updated 2 taps (caskroom/cask, homebrew/core).
==> New Formulae
dscanner
==> Updated Formulae
abi-compliance-checker     go ✔                       mg  
asciinema2gif              godep                      mpv  
ccextractor                gollum                     node  
datomic                    govendor                   planck  
exploitdb                  gpm                        qscintilla2  
flatbuffers                jpegoptim                  s-search  
gammu                      kitchen-sync               tippecanoe  
gdm                        libmill  
glide                      m-cli  
==> Deleted Formulae
fugu
==> Installing parity from ethcore/ethcore
==> Cloning https://github.com/ethcore/parity.git
Updating /Users/rdelgado/Library/Caches/Homebrew/parity--git
==> Checking out branch stable
==> multirust update stable
Last 15 lines from /Users/rdelgado/Library/Logs/Homebrew/parity/01.multirust:
2016-08-16 14:29:41 -0400

multirust update stable

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/ethcore/homebrew-ethcore/issues

**Comment by debris** [comment]
Can't see the error here. Can you run `brew install --verbose parity`?

**Comment by unimercio** [comment]
thanks, here it is --verbose
...............
Enriques-Air:~ rdelgado$ brew tap ethcore/ethcore
Enriques-Air:~ rdelgado$ brew install --verbose parity
==> Auto-updated Homebrew!
Updated Homebrew from 984ed83 to b39eba6.
Updated 4 taps (caskroom/cask, ethcore/ethcore, homebrew/core, homebrew/versions).
==> New Formulae
homebrew/versions/go16                   jxrlib                                 
==> Updated Formulae
ammonite-repl       flake8              libjson-rpc-cpp ✔   siege             
artifactory         gnupg               libpng              translate-toolkit 
awscli              jenkins             node-build          unrar             
brotli              libftdi             pillar              xonsh             
calabash            libgcrypt           radare2             youtube-dl        
citus               libgit2-glib        rancher-compose   
==> Installing parity from ethcore/ethcore
==> Cloning https://github.com/ethcore/parity.git
Updating /Users/rdelgado/Library/Caches/Homebrew/parity--git
git config remote.origin.url https://github.com/ethcore/parity.git
git config remote.origin.fetch +refs/heads/stable:refs/remotes/origin/stable
git fetch origin
==> Checking out branch stable
git checkout -f stable --
Already on 'stable'
Your branch is up-to-date with 'origin/stable'.
git reset --hard origin/stable
HEAD is now at a66fd11 Merge pull request #1887 from ethcore/stable-staging
git submodule foreach --recursive git submodule sync
Entering 'ethcore/res/ethereum/tests'
git submodule update --init --recursive
==> multirust update stable
Failed to execute: multirust update stable
==> Formula
Tap: ethcore/ethcore
Path: /usr/local/Library/Taps/ethcore/homebrew-ethcore/parity.rb
==> Configuration
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b39eba6c5f0f6f1b19e663df52bc72b9d8518886
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d20c2c0ca298422adf373e48e243a1cdba652e6f
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 1.8.3.1 => /usr/local/git/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_102, 1.7.0_79, 1.6.0_65-b14-466.1
OS X: 10.10.5-x86_64
Xcode: N/A
CLT: 7.2.0.0.1.1447826929
X11: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/Homebrew/os/mac/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/Homebrew/shims/super:/usr/local/opt/multirust/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

Error: ethcore/ethcore/parity 1.2.4 did not build
Logs:
     /Users/rdelgado/Library/Logs/Homebrew/parity/01.multirust

**Comment by rphmeier** [comment]
Seems that the installed version of `multirust` is failing to update the rust compiler. The log indicated at `/Users/rdelgado/Library/Logs/Homebrew/parity/01.multirust` could help us diagnose the issue.

Side note: is there a brew package for `rustup`?

**Comment by debris** [comment]
> Side note: is there a brew package for `rustup`?

No

> Seems that the installed version of multirust is failing to update the rust compiler. The log indicated at `/Users/rdelgado/Library/Logs/Homebrew/parity/01.multirust` could help us diagnose the issue.

@unimercio can you paste the content of the file here? Also, do you have rust installed on your machine? Multirust conflicts with rust and this may be the reason of failing build

**Comment by unimercio** [comment]
> @unimercio can you paste the content of the file here? Also, do you have rust installed on your machine? Multirust conflicts with rust and this may be the reason of failing build

GNU nano 2.0.6 File: ...o/Library/Logs/Homebrew/parity/01.multirust           

2016-08-18 09:49:31 -0400

multirust update stable

Failed to execute: multirust update stable

HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b39eba6c5f0f6f1b19e663df52bc72b9d8518886
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d20c2c0ca298422adf373e48e243a1cdba652e6f
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p481

**Comment by arkpar** [comment]
perhaps `brew reinstall multirust` would help

**Comment by unimercio** [comment]
>  @unimercio can you paste the content of the file here? Also, do you have rust installed on your machine? Multirust conflicts with rust and this may be the reason of failing build

@debris  I uninstalled multirust using
`sudo brew uninstall --force multirust`
Uninstalling multirust... (62 files, 116.6M)

I then ran:
`brew install parity --verbose`

   Compiling serde_codegen v0.7.9
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `ethcore-ipc-codegen v1.2.0 (file:///private/tmp/parity-20160818-20718-1stb19v/ipc/codegen)`
Process didn't exit successfully: `/private/tmp/parity-20160818-20718-1stb19v/target/release/build/ethcore-ipc-codegen-ba5b8b2397065840/build-script-build` (signal: 6, SIGABRT: process abort signal)
--- stderr

thread '<main>' has overflowed its stack
fatal runtime error: stack overflow

==> Formula
Tap: ethcore/ethcore
Path: /usr/local/Library/Taps/ethcore/homebrew-ethcore/parity.rb
==> Configuration
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b39eba6c5f0f6f1b19e663df52bc72b9d8518886
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d20c2c0ca298422adf373e48e243a1cdba652e6f
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 1.8.3.1 => /usr/local/git/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_102, 1.7.0_79, 1.6.0_65-b14-466.1
OS X: 10.10.5-x86_64
Xcode: N/A
CLT: 7.2.0.0.1.1447826929
X11: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/Homebrew/os/mac/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/Homebrew/shims/super:/usr/local/opt/multirust/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

Error: ethcore/ethcore/parity 1.2.4 did not build

**Comment by unimercio** [comment]
@arkpar is was not able to run the reinstall with or without sudo

Enriques-Air:~ rdelgado$ brew reinstall multirust
==> Reinstalling multirust
==> Downloading https://homebrew.bintray.com/bottles/multirust-0.8.0_1.yosemite.
######################################################################## 100.0%
==> Pouring multirust-0.8.0_1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/multirust/0.8.0_1: 15 files, 166.6K
Error: Permission denied - /usr/local/Cellar/multirust/0.8.0_1.reinstall/lib/rustlib/etc/debugger_pretty_printers_common.py
Enriques-Air:~ rdelgado$ sudo brew reinstall multirust
Password:
Error: Cowardly refusing to 'sudo brew reinstall'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
Enriques-Air:~ rdelgado$ sudo brew reinstall multirust
Error: Cowardly refusing to 'sudo brew reinstall'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at

**Comment by debris** [comment]
please try

```
unset TMPDIR
brew install parity --verbose
```

It should help with `ethcore-ipc-codegen` issue

**Comment by unimercio** [comment]
Thanks @debris , here is result

**Ran:**
$ unset TMPDIR
$ brew install parity --verbose

==> Installing parity from ethcore/ethcore
==> Cloning https://github.com/ethcore/parity.git
Updating /Users/rdelgado/Library/Caches/Homebrew/parity--git
git config remote.origin.url https://github.com/ethcore/parity.git
git config remote.origin.fetch +refs/heads/stable:refs/remotes/origin/stable
git fetch origin
==> Checking out branch stable
git checkout -f stable --
Already on 'stable'
Your branch is up-to-date with 'origin/stable'.
git reset --hard origin/stable
HEAD is now at a66fd11 Merge pull request #1887 from ethcore/stable-staging
git submodule foreach --recursive git submodule sync
Entering 'ethcore/res/ethereum/tests'
git submodule update --init --recursive
==> multirust update stable
Failed to execute: multirust update stable
==> Formula
Tap: ethcore/ethcore
Path: /usr/local/Library/Taps/ethcore/homebrew-ethcore/parity.rb
==> Configuration
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: fa19447a2d9d311909452ee35b309d08558c9a3a
Last commit: 89 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bf3f3d00bfa2e83bad087cb8187b82295884d08a
Core tap last commit: 56 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p645
Clang: 7.3 build 703
Git: 1.8.3.1 => /usr/local/git/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_102, 1.7.0_79
OS X: 10.11.3-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
MACOSX_DEPLOYMENT_TARGET: 10.11
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/Homebrew/os/mac/pkgconfig/10.11
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/Homebrew/shims/super:/usr/local/opt/multirust/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

Error: ethcore/ethcore/parity 1.2.4 did not build
Logs:
     /Users/rdelgado/Library/Logs/Homebrew/parity/01.multirust

**Log follows:**
  GNU nano 2.0.6 File: ...o/Library/Logs/Homebrew/parity/01.multirust           

Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: N/A

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/D$
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.fram$
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Curren$
MACOSX_DEPLOYMENT_TARGET: 10.11
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/Homebrew/os/mac/pkgcon$
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/Homebrew/shims/super:/usr/local/opt/multirust/bin:/usr$

**Comment by tjayrush** [comment]
I'm having the same problem on Mac OS X 10.10.5

I tried 'unset TMPDIR' and then 'brew install parity --verbose' Here's the end of the output (it seems to have gone pretty far through the build):

[Parity Failed Build.txt](https://github.com/ethcore/parity/files/437349/Parity.Failed.Build.txt)

**Comment by tjayrush** [comment]
I don't know if this is helpful (I hope it is). I'm new to rust, but I found 'cargo' which is working fine for me with simple programs. When I try to build with cargo (> cargo build ) I get a similar problem with serde. I also tried setting RUST_MIN_STACK but that didn't help. Here's the output from verbose: 
[Cargo Failed Build.txt](https://github.com/ethcore/parity/files/437892/Cargo.Failed.Build.txt)

**Comment by debris** [comment]
@tjayrush your issue is already fixed on master. I opened 2 prs to backport the fix to stable and beta branches ( #2030 and #2031 ).

**Comment by arkpar** [comment]
Please reopen if this is still failing

**Comment by tjayrush** [comment]
It still fails. Pretty much exactly as it did before. Here’s what I did:

	brew install parity --verbose

Very long build with lots of downloads, failed here:

	Compiling serde_codegen v0.7.9
	Build failed, waiting for other jobs to finish...
	Build failed, waiting for other jobs to finish...
	error: failed to run custom build command for `ethcore-ipc-codegen v1.2.0
		(file:///private/tmp/parity-20160913-17684-54imjr/ipc/codegen)`
	process didn't exit successfully: `/private/tmp/parity-20160913-17684-54imjr/
	target/release/build/ethcore-ipc-codegen-f67e6e4eef5744b4/build-script-build`
	(signal: 6, SIGABRT: process abort signal)

	--- stderr

	thread 'main' has overflowed its stack
	fatal runtime error: stack overflow

Then I did this:

	brew install ethcore/ethcore

and it told me it couldn’t build because I had to first run this command (which I did);

	brew link --overwrite multirust

but that didn’t work (saying no permission) so I did this:

	sudo chmod o+w /usr/local/lib
	sudo chmod o+w /usr/local/rustlib

and then linking multirust worked with a message similar to this:

	....created 13 links

Then I reran tried to re-run this:

	brew tap ethcore/ethcore

it worked. Then I did this:

	export RUST_MIN_STACK=100000000
	brew install parity --verbose

Went through a long build with lots of downloads and failed one line later than before:

	...
	Compiling quasi_codegen v0.11.0
	Compiling ethcore-ipc-codegen v1.2.0 (file:///private/tmp/parity-20160913-34951-gjln6h/ipc/codegen)
	Compiling serde_codegen v0.7.9
	Compiling parity-dapps v0.6.0 (https://github.com/ethcore/parity-ui.git#7120546d)
	Build failed, waiting for other jobs to finish...
	Build failed, waiting for other jobs to finish...
	error: failed to run custom build command for `serde_codegen v0.7.9`
	process didn't exit successfully: `/private/tmp/parity-20160913-34951-gjln6h/target/release/build/
	serde_codegen-2b96ef9db45a9924/	build-script-build` (signal: 6, SIGABRT: process abort signal)
	--- stderr

	thread 'main' has overflowed its stack
	fatal runtime error: stack overflow

So I increased the stack environment varialbe (beause I didn’t know what else to do):

	export RUST_MIN_STACK=100000000
	brew install parity --verbose


And got same exact error. So then I quit. By the way, this is nearly identical to how it was failing earlier.

And now I would like to re-open this bug

**Comment by 5chdn** [comment]
Do the builds still fail for you?

If yes, could you check whether `--beta` builds also fail? 

    brew install parity --beta --verbose

**Comment by dwking2000** [comment]
I'm having the same issue.

==> Checking OS dependencies
 ✓	 OS X Version 10.10.5
 ✓	 git
 ✓	 Ruby 2.0.0
 ✓	 Homebrew 1.1.5
Homebrew/homebrew-core (git revision 4cfbf8; last commit 2016-12-22)

Found all dependencies (4/4)
==> OK, let's install Parity now!
==> Last chance! Sure you want to install this software? [Y/n] Y

==> Installing Parity build dependencies
==> Adding ethcore repository
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 5 taps (ethcore/ethcore, ethereum/ethereum, homebrew/binary, homebrew/core, homebrew/versions).
==> New Formulae

..... then bunch of updating of formulae and then 


==> Updating brew
Updated 1 tap (phinze/cask).

==> Installing parity
==> Reinstalling ethcore/ethcore/parity
==> Cloning https://github.com/ethcore/parity.git
Updating /Users/kingdo/Library/Caches/Homebrew/parity--git
==> Checking out tag v1.4.12
==> multirust update stable
==> multirust run stable cargo build --release

at this point the update hangs. 

I have had this problem with previous versions of  Parity and never was able to install it. I have come back occasionally to see if new versions fix this, but it seems it's not a Parity issue but the brew install or some other configuration issue. Please advise.

**Comment by 5chdn** [comment]
@dwking2000 it does not hang, it just takes a while, on some machines up to 30-40 minutes.

Run brew with `--verbose` flag to see the what multirust is actually doing.
